<form action="newUserAttribute" method="post">
    <div>
        <div class="user_Attributes">
            User attribute name <input type="text" id="userAttrName" name="userAttrName">
            <br>
            User attribute value <input type="text" id="userAttrValue" name="userAttrValue">
            <br> <br> <br>
            <input type="submit" class="newPassword" value="new Attribute" name="submit" class="button">
            <a href="" class="Close">Close</a>
        </div>
    </div>
</form>