<?php
?>
<div class="aboutProduct" >

    <p >
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua . Ac tortor dignissim convallis aenean et tortor . A condimentum vitae sapien pellentesque habitant
        morbi tristique . Eget egestas purus viverra accumsan in nisl . Donec et odio pellentesque diam volutpat commodo
        sed egestas . Eget nulla facilisi etiam dignissim diam quis enim . Sit amet facilisis magna etiam tempor orci eu
        lobortis elementum . Amet cursus sit amet dictum sit amet justo . Commodo quis imperdiet massa tincidunt nunc .
Porttitor lacus luctus accumsan tortor posuere ac . Ultrices mi tempus imperdiet nulla malesuada . Justo nec
        ultrices dui sapien eget mi proin . Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin . Nec feugiat
        nisl pretium fusce id velit ut tortor . Tellus integer feugiat scelerisque varius morbi . Quisque non tellus orci
        ac auctor augue mauris augue .
    </p >
</div >