<div class="auth">

    <div class="center">
        <div class="d1">
            <?php require 'app/template/partial/signUp.phtml' ?>
            <?php require 'app/template/partial/logIn.phtml' ?>
        </div>
        <div class="d2">
            <div class="SignUpOption">
                <div class="SignUpDescr">
                    <p>Don't have an account?</p>
                    <hr class="underLine">
                    <p class="loginDescription">
                        Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsumipsum Lorem ipsum Lorem
                        ipsum
                        Lorem ipsum
                    </p>
                    <input type="button" value="Sign Up" id="enterSignUp">
                </div>
            </div>
            <div class="rightOption">
                <div class="rightContent">
                    <p class="rightTitle">Don't have an account?</p>
                    <hr class="rightUnderLine">
                    <p class="rightDescription">
                        Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsumipsum Lorem ipsum Lorem
                        ipsum
                        Lorem ipsum
                    </p>
                    <input type="button" value="Log in" id="enterLogin">
                </div>
            </div>
        </div>

    </div>
</div>
