<div class="log">
    <form action="login" method="post">

        <div class="leftOption ">

            <div class="loginContent">
                <div class="loginTitle">
                    <p>Log in</p>
                    <img class="Logo" src="app/pub/media/Magebitlogo.png">
                </div>
                <hr>
                <div class="rightEmail">
                    <div class="mailInput">
                        <div class="inputSize">
                            <input id="LogInEmail" name="email" type="text"
                                   placeholder="Email"/>
                        </div>
                        <img class="mail" src="app/pub/media/mail.png">
                    </div>

                </div>
                <div class="rightPassword">
                    <div class="inputPass">
                        <div class="inputSize">
                            <input id="LogInPassword" name="password" type="password"
                                   placeholder="Password"/>
                            <label for="LogInPassword" id="labelPassword"></label>
                        </div>
                        <img class="lock" src="app/pub/media/lock.png">
                    </div>

                </div>

                <div class="LogInButtons">
                    <input type="submit" name="login" value="LOGIN" id="signIN">
                    <a href="">Forgot?</a>
                    <input type="submit" value="Sign Up" name="login" id="enterSignUp2">
                </div>
            </div>


        </div>


    </form>
</div>