<div class="sign">
    <form action="signup" method="post">

        <div class="signUp">

            <div class="leftContent">
                <div class="titleLeft">
                    <p>Sign UP</p>
                    <img class="Logo" src="app/pub/media/Magebitlogo.png">
                </div>
                <hr>

                <div class="leftName">
                    <div class="nameInput">
                        <div class="inputSize">
                            <input type="text" id="SignupName" name="newName" placeholder="Name"/>
                        </div>
                        <img class="user" src="app/pub/media/user.png">
                    </div>

                </div>

                <div class="leftEmail">
                    <div class="emailInput">
                        <div class="inputSize">
                            <input type="text" id="LogInEmail" name="newEmail" placeholder="Email"/>
                        </div>
                        <img class="mail" src="app/pub/media/mail.png">
                    </div>

                </div>
                <div class="leftPassword">
                    <div class="inputPass">
                        <div class="inputSize">
                            <input id="LogInPassword" name="Password" type="password"
                                   placeholder="Password"/>
                        </div>
                        <img class="lock" src="app/pub/media/lock.png">
                    </div>
                </div>

                <div class="leftButtons">
                    <input type="submit" name="signup" value="Sign Up" id="signIN">
                </div>
            </div>

        </div>

        <!---->
    </form>
</div>